# BUILD
FROM node:12.7-alpine AS build
RUN mkdir -p /app
WORKDIR /app

COPY package*.json /app
RUN npm install

COPY . /app
RUN npm run build

# RUN
FROM nginx:1.17.1-alpine
COPY --from=build app/dist/CarRentalSystem /usr/share/nginx/html

expose 80