apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: modeler-ojt
spec:
  selector:
    matchLabels:
      app: frontend
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
        track: stable
    spec:
      containers:
        - name: nginx
          image: "sosdong/ojt-frontend:0.3"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]